"""SyntheticRepository — the default backend. Domain tables are read from a local
DuckDB store (generated by `nexo_os.data.generate`); system tables (acciones,
agent_runs, audit_log) are read/written in a separate runtime DuckDB store so that
regenerating synthetic data never wipes approvals or the audit log.

Implements every method of NexoRepository with real SQL over the canonical schema.
"""

from __future__ import annotations

from collections.abc import Sequence
from datetime import date, datetime
from pathlib import Path

import duckdb

from nexo_os.config import get_settings
from nexo_os.data.models import (
    Accion,
    AccionEstado,
    AgentRun,
    Aseguradora,
    AuditEvent,
    Cliente,
    ClienteEstado,
    Comision,
    ComisionEstado,
    Cotizacion,
    CotizacionEstado,
    Cuota,
    CuotaEstado,
    EntidadTipo,
    Interaccion,
    Lead,
    LeadEstado,
    Poliza,
    PolizaEstado,
    Productor,
    Ramo,
    RunEstado,
    Siniestro,
    SiniestroEstado,
    _Base,
)
from nexo_os.data.repository import DataSourceUnavailable, NexoRepository
from nexo_os.data.schema_def import SYSTEM_TABLES, TABLES_BY_NAME, render_duckdb_ddl

_SYSTEM_DDL = "\n".join(
    f"CREATE TABLE IF NOT EXISTS {t.name} ("
    + ", ".join(f"{c.name} {c.duck_type}" for c in t.columns)
    + (
        f", PRIMARY KEY ({', '.join(c.name for c in t.columns if c.pk)})"
        if any(c.pk for c in t.columns)
        else ""
    )
    + ");"
    for t in SYSTEM_TABLES
)


def _cols(table: str) -> list[str]:
    return [c.name for c in TABLES_BY_NAME[table].columns]


def _rows_to_models(cur: duckdb.DuckDBPyConnection, model: type[_Base]) -> list:
    names = [d[0] for d in cur.description]
    return [model(**dict(zip(names, row, strict=True))) for row in cur.fetchall()]


class SyntheticRepository(NexoRepository):
    data_source = "synthetic"

    def __init__(
        self,
        synthetic_db_path: Path | None = None,
        runtime_db_path: Path | None = None,
        snapshot_fecha: date | None = None,
    ) -> None:
        settings = get_settings()
        self._dom_path = synthetic_db_path or settings.synthetic_db_path
        self._rt_path = runtime_db_path or settings.runtime_db_path
        self._snapshot = snapshot_fecha or settings.snapshot_fecha

        if not self._dom_path.exists():
            raise DataSourceUnavailable(
                f"Synthetic store not found at {self._dom_path}. "
                "Run `python -m nexo_os seed` first."
            )
        self._dom = duckdb.connect(str(self._dom_path), read_only=True)

        self._rt_path.parent.mkdir(parents=True, exist_ok=True)
        self._sys = duckdb.connect(str(self._rt_path))
        self._sys.execute(_SYSTEM_DDL)

    @property
    def snapshot_fecha(self) -> date:
        return self._snapshot

    # --- generic helpers ------------------------------------------------------

    def _select(
        self,
        con: duckdb.DuckDBPyConnection,
        table: str,
        model: type[_Base],
        where: Sequence[str] = (),
        params: Sequence[object] = (),
        order_by: str | None = None,
    ) -> list:
        cols = ", ".join(_cols(table))
        sql = f"SELECT {cols} FROM {table}"
        if where:
            sql += " WHERE " + " AND ".join(where)
        if order_by:
            sql += f" ORDER BY {order_by}"
        cur = con.execute(sql, list(params))
        return _rows_to_models(cur, model)

    @staticmethod
    def _eq(col: str, value: object, where: list[str], params: list[object]) -> None:
        if value is not None:
            where.append(f"{col} = ?")
            params.append(str(value) if hasattr(value, "value") else value)

    # --- domain reads ---------------------------------------------------------

    def get_clientes(self, estado: ClienteEstado | None = None) -> list[Cliente]:
        where: list[str] = []
        params: list[object] = []
        self._eq("estado", estado, where, params)
        return self._select(self._dom, "clientes", Cliente, where, params)

    def get_polizas(
        self, estado: PolizaEstado | None = None, ramo: Ramo | None = None
    ) -> list[Poliza]:
        where: list[str] = []
        params: list[object] = []
        self._eq("estado", estado, where, params)
        self._eq("ramo", ramo, where, params)
        return self._select(self._dom, "polizas", Poliza, where, params)

    def get_cuotas(self, estado: CuotaEstado | None = None) -> list[Cuota]:
        where: list[str] = []
        params: list[object] = []
        self._eq("estado", estado, where, params)
        return self._select(self._dom, "cuotas", Cuota, where, params)

    def get_comisiones(
        self, periodo: str | None = None, estado: ComisionEstado | None = None
    ) -> list[Comision]:
        where: list[str] = []
        params: list[object] = []
        self._eq("periodo", periodo, where, params)
        self._eq("estado", estado, where, params)
        return self._select(self._dom, "comisiones", Comision, where, params)

    def get_leads(self, estado: LeadEstado | None = None) -> list[Lead]:
        where: list[str] = []
        params: list[object] = []
        self._eq("estado", estado, where, params)
        return self._select(self._dom, "leads", Lead, where, params)

    def get_cotizaciones(self, estado: CotizacionEstado | None = None) -> list[Cotizacion]:
        where: list[str] = []
        params: list[object] = []
        self._eq("estado", estado, where, params)
        return self._select(self._dom, "cotizaciones", Cotizacion, where, params)

    def get_siniestros(self, estado: SiniestroEstado | None = None) -> list[Siniestro]:
        where: list[str] = []
        params: list[object] = []
        self._eq("estado", estado, where, params)
        return self._select(self._dom, "siniestros", Siniestro, where, params)

    def get_aseguradoras(self) -> list[Aseguradora]:
        return self._select(self._dom, "aseguradoras", Aseguradora)

    def get_productores(self) -> list[Productor]:
        return self._select(self._dom, "productores", Productor)

    def get_interacciones(self, entidad_tipo: EntidadTipo | None = None) -> list[Interaccion]:
        where: list[str] = []
        params: list[object] = []
        self._eq("entidad_tipo", entidad_tipo, where, params)
        return self._select(self._dom, "interacciones", Interaccion, where, params)

    # --- acciones -------------------------------------------------------------

    def _insert(self, table: str, items: Sequence[_Base]) -> None:
        if not items:
            return
        cols = _cols(table)
        placeholders = ", ".join("?" for _ in cols)
        sql = f"INSERT INTO {table} ({', '.join(cols)}) VALUES ({placeholders})"
        rows = [[_param(getattr(it, c)) for c in cols] for it in items]
        self._sys.executemany(sql, rows)

    def insert_acciones(self, acciones: list[Accion]) -> None:
        self._insert("acciones", acciones)

    def get_acciones(
        self, estado: AccionEstado | None = None, run_id: str | None = None
    ) -> list[Accion]:
        where: list[str] = []
        params: list[object] = []
        self._eq("estado", estado, where, params)
        self._eq("run_id", run_id, where, params)
        return self._select(self._sys, "acciones", Accion, where, params, order_by="creada_en")

    def get_accion(self, accion_id: str) -> Accion | None:
        rows = self._select(self._sys, "acciones", Accion, ["accion_id = ?"], [accion_id])
        return rows[0] if rows else None

    def resolve_accion(
        self,
        accion_id: str,
        estado: AccionEstado,
        resuelta_en: datetime,
        resuelta_por: str,
        nota_revisor: str | None = None,
        mensaje_es: str | None = None,
    ) -> None:
        if mensaje_es is None:
            self._sys.execute(
                "UPDATE acciones SET estado = ?, resuelta_en = ?, resuelta_por = ?, "
                "nota_revisor = ? WHERE accion_id = ?",
                [str(estado), resuelta_en, resuelta_por, nota_revisor, accion_id],
            )
        else:
            self._sys.execute(
                "UPDATE acciones SET estado = ?, resuelta_en = ?, resuelta_por = ?, "
                "nota_revisor = ?, mensaje_es = ? WHERE accion_id = ?",
                [str(estado), resuelta_en, resuelta_por, nota_revisor, mensaje_es, accion_id],
            )

    # --- agent_runs -----------------------------------------------------------

    def insert_agent_run(self, run: AgentRun) -> None:
        self._insert("agent_runs", [run])

    def update_agent_run(
        self, run_id: str, finalizado_en: datetime, estado: RunEstado, resumen_json: str
    ) -> None:
        self._sys.execute(
            "UPDATE agent_runs SET finalizado_en = ?, estado = ?, resumen_json = ? "
            "WHERE run_id = ?",
            [finalizado_en, str(estado), resumen_json, run_id],
        )

    def get_agent_runs(self) -> list[AgentRun]:
        return self._select(self._sys, "agent_runs", AgentRun, order_by="iniciado_en")

    # --- audit_log (append-only, hash-chained) --------------------------------

    def append_audit_event(self, event: AuditEvent) -> None:
        self._insert("audit_log", [event])

    def get_audit_events(self) -> list[AuditEvent]:
        return self._select(self._sys, "audit_log", AuditEvent, order_by="rowid")

    def get_last_audit_hash(self) -> str | None:
        row = self._sys.execute("SELECT hash FROM audit_log ORDER BY rowid DESC LIMIT 1").fetchone()
        return row[0] if row else None

    # --- maintenance ----------------------------------------------------------

    def close(self) -> None:
        self._dom.close()
        self._sys.close()


def _param(value: object) -> object:
    """Coerce a model attribute to a DuckDB-friendly parameter."""
    return str(value) if hasattr(value, "value") else value  # StrEnum -> str


def init_synthetic_store(con: duckdb.DuckDBPyConnection) -> None:
    """Create the full domain+system schema in a synthetic DuckDB connection.
    Used by the generator before loading rows."""
    con.execute(render_duckdb_ddl())
